### ISSUE TITLE
Access phpmyadmin

### ISSUE THREAD

**Issue by developcreativo** [deck-app/lamp-stack#2]
![image](https://user-images.githubusercontent.com/5873347/177150377-465b6941-4870-4681-a5f4-18995778b363.png)
credentials example

**Comment by nabad600** [comment]
Hi @developcreativo, 
Let me know you are using DECK app or run this repository from terminal.

Thank you

**Comment by nabad600** [comment]
Hi @developcreativo, 
Thanks for your valuable feedback, on the below-mentioned process.
https://www.loom.com/share/3a6c1796018e473b8ba45932a3e2df2b
